real: True
T_burnin: 10 
alpha: 0.2
Quantiles_given: True 
multiple_series: False 
asymmetric: False
sequences:
  0:
    dataset: "COVID-national-cases-1wk"
    log: False
methods:
  Trail:
    weight_length: 10 
  ACI:
    lrs:
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
    window_length: 100000 
  Quantile:
    lrs:
      - 1000000 
      - 100000 
      - 10000 
      - 1000 
      - 100 
  Quantile_integrator_log:
    lrs:
      - 1000000 
      - 100000 
      - 10000 
      - 1000 
      - 100 
    Csat: 0.05 
    KI: 200000 
  Quantile_integrator_log_scorecaster:
    lrs:
      - 1000000 
      - 100000 
      - 10000 
      - 1000 
      - 100 
    Csat: 0.05 
    KI: 200000 
    steps_ahead: 1 
