real: True
quantiles_given: False
multiple_series: False 
T_burnin: 500 
alpha: 0.1
seasonal_period: 365
asymmetric: False
sequences:
  0:
    dataset: "daily-climate"
    fit_every: 30 
    log: False
    order:
      - 3 
      - 0
      - 0
    window_length: 10 
    overwrite: False 
methods:
  trail:
    weight_length: 50 
  aci:
    lrs:
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
    window_length: 10000000 
  quantile:
    lrs:
      - 1 
      - 0.2
      - 0.05
      - 0.01
      - 0.001
  quantile_integrator_log:
    lrs:
      - 1 
      - 0.2
      - 0.05
      - 0.01
      - 0.001
    Csat: 5 
    KI: 10 
  quantile_integrator_log_scorecaster:
    lrs:
      - 1 
      - 0.2
      - 0.05
      - 0.01
      - 0.001
    Csat: 5 
    KI: 10 
    steps_ahead: 1 
