real: True
Quantiles_given: False
multiple_series: False 
T_burnin: 100 
alpha: 0.1
seasonal_period: 5
asymmetric: False
sequences:
  0:
    dataset: "GOOGL"
    fit_every: 15
    log: True
    order:
      - 3 
      - 0
      - 0
    window_length: 10 
    overwrite: False 
methods:
  Trail:
    weight_length: 50 
  ACI:
    lrs:
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
    window_length: 10000000 
  Quantile:
    lrs:
      - 40 
      - 20 
      - 5 
      - 1 
      - 0.1 
  Quantile_integrator_log:
    lrs:
      - 40 
      - 20 
      - 5 
      - 1 
      - 0.1 
    Csat: 1 
    KI: 200 
  Quantile_integrator_log_scorecaster:
    lrs:
      - 40 
      - 20 
      - 5 
      - 1 
      - 0.1 
    Csat: 1 
    KI: 200 
    steps_ahead: 1 
